language: php

php:
  - 5.3
  - 5.4

env:
  - SYMFONY_VERSION=origin/2.2

before_script:
  - composer install --dev --prefer-source

script: phpunit

notifications:
    webhooks: http://sonata-project.org/bundles/news/master/travis
